### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by yellow-starburst** [seajaysec/cypheroth#21]
Some of the queries broke with the following error:
`Could not initialize class org.eclipse.collections.impl.utility.LazyIterate`

**Comment by seajaysec** [comment]
Could you share more detailed log output around what generated this error? Feel free to redact any sensitive info from the domain. Just wondering which queries and if there's anything else that can help pin down what's happening here.

Also, could you share the output of `cypher-shell -v`? Thanks!

**Comment by yellow-starburst** [comment]
It turned out to be a broken neo4j instance. Restarted the host and worked. Closing
