### ISSUE TITLE
Bad Substitution

### ISSUE THREAD

**Issue by mubix** [seajaysec/cypheroth#3]
`./cypheroth.sh: line 50: ${DOMAIN^^}: bad substitution`

for command line: `./cypheroth.sh -u neo4j -p neo4j -d domainhere.com`

**Comment by mubix** [comment]
This is running on a Mac which might have a slightly different version of Bash

**Comment by seajaysec** [comment]
Hi @mubix. I made an update today that, among other things, does away with that line and relies on the user to provide the proper case sensitivity for the FQDN. Hopefully that also improves its compatibility with the older version of Bash that runs on Macs.

Would you be able to update and try the current version?

**Comment by seajaysec** [comment]
I was able to test this out on a mac with older bash installed and found a few things that still needed cleaning up. Just pushed a fix that should be compatible with bash versions 3.2.57 (old version that ships on mac) through 5.0.11 (new version, installable on mac with homebrew).

**Comment by mubix** [comment]
Works like a charm. Thanks!
