### ISSUE TITLE
Timeout Issues

### ISSUE THREAD

**Issue by mubix** [seajaysec/cypheroth#5]
Not sure how to describe this one, but basically some of the queries can result in essentially a DoS of the Neo4J database when there are too many results. Is there a way to limit the results to Top 10,000 or something like that?

For example the queries `User that are admin on 1+ machines, sorted by admin count` seems to peg the java process and never return on my example domain.

**Comment by mubix** [comment]
I've added `dbms.transaction.timeout=10m` to my neo4j.conf to see if I can at least get through the script even if there are some queries that don't finish.

**Comment by seajaysec** [comment]
> I've added dbms.transaction.timeout=10m to my neo4j.conf to see if I can at least get through the script even if there are some queries that don't finish.

Nice temp fix. I haven't had a database that large to test with. I get what you're saying though, and will look into figuring out a solution for it. May not have time to address it right away though.

Also, thanks for submitting these bug reports! They've definitely been helping me improve this script a lot.

**Comment by seajaysec** [comment]
@mubix, ~check out the [dev branch](https://github.com/seajaysec/cypheroth/tree/dev) and~ let me know if this helps. I've added in a timeout flag that lets the user determine how long they're willing to wait for a query before moving on to the next one.

There might also be a way to solve this the way you originally proposed, however. I'll ask around on the bloodhound slack and see if anyone knows. In the meantime, if you find a query that performs better for you in the neo4j web terminal than the version in this script, please share it and I'll make an update.

**Comment by seajaysec** [comment]
Checked with the Bloodhound folks and it's not possible to return partial query results. The next best option that I've found is to time out the query. I was able to generate a sample dataset with 100k nodes and tested this out pretty thoroughly, so I'm now merging it in to the master branch.

**Comment by mubix** [comment]
Thanks a ton for doing the testing and making the changes. It's helped out a lot.

**Comment by seajaysec** [comment]
Yeah for sure! Glad it’s helping out. Thanks again for letting me know that this was an issue.
