### ISSUE TITLE
Trailing characters in csv output

### ISSUE THREAD

**Issue by samuellg** [seajaysec/cypheroth#8]
Hi @seajaysec,
Thanks for you script, it's pretty useful! There is an issue in the output in csv files. As the `tr -d '"' <$SAVEPATH 1<>$SAVEPATH` rewrites in the file without erasing its content, with less characters, you still have a few lines of duplicate results with quoted results at the end. Like :
[...]
USER@DOMAIN.COM
USER2@DOMAIN.COM
"USER2@DOMAIN.COM"

Replacing this line with `sed -i 's/"//g' $SAVEPATH` fixes this.

**Comment by seajaysec** [comment]
Ohh that explains that. Thanks. I might use tr to replace them with spaces. I can’t seem to figure out a sed replace command that works with the same syntax on mac and linux. Same deal with awk. Been wrasslin with that for a while, which is how I landed on tr.

**Comment by seajaysec** [comment]
Fixed in [v1.4.08](https://github.com/seajaysec/cypheroth/commit/6ed69e39a8da37350c72231f5d74cd96ee40a7e7)! Thanks again for submitting this issue.
